// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXZfQrwOPytKF1DPgawhoLVe-6A5NcTPA',
    appId: '1:835831988787:web:6a1c093c2fa578eb0ed946',
    messagingSenderId: '835831988787',
    projectId: 'e-book-store-1c66f',
    authDomain: 'e-book-store-1c66f.firebaseapp.com',
    storageBucket: 'e-book-store-1c66f.appspot.com',
    measurementId: 'G-KN3VMRL9QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeyAlkhETMZT4etYlsHd37HV_UFqvJjXQ',
    appId: '1:835831988787:android:46845eee263ec0ef0ed946',
    messagingSenderId: '835831988787',
    projectId: 'e-book-store-1c66f',
    storageBucket: 'e-book-store-1c66f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5wEHXQQdG-Gaz4Q1DYBmr34BwPYwOuzU',
    appId: '1:915402983493:ios:9c47fc0a0af6f9c91c3b2c',
    messagingSenderId: '915402983493',
    projectId: 'e-book-store-83a48',
    storageBucket: 'e-book-store-83a48.appspot.com',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5wEHXQQdG-Gaz4Q1DYBmr34BwPYwOuzU',
    appId: '1:915402983493:ios:6088b94a0449f5761c3b2c',
    messagingSenderId: '915402983493',
    projectId: 'e-book-store-83a48',
    storageBucket: 'e-book-store-83a48.appspot.com',
    iosBundleId: 'com.example.eBook.RunnerTests',
  );
}